insert into categories(name,slug,position) values ('Mieszkalne','mieszkalne',1),('Modułowe','modulowe',2),('Biurowe','biurowe',3),('Usługowe','uslugowe',4),('Gastronomiczne','gastronomiczne',5),('Rekreacyjne','rekreacyjne',6),('Całoroczne','caloroczne',7) on conflict do nothing;
with c as(select id,name from categories), ins as(insert into products(category_id,name,slug,short_description,description,price_from,area,dimensions,rooms,bedrooms,purpose,featured,status,published_at) values
((select id from c where name='Rekreacyjne'),'MODERN 20','modern-20','Kompaktowy moduł rekreacyjny z kompletnymi instalacjami.','Gotowy moduł dopasowany do odpoczynku.',89900,20,'6,0 × 3,35 m',1,0,array['rekreacja'],false,'PUBLISHED',now()),
((select id from c where name='Mieszkalne'),'LIVING 25','living-25','Całoroczny moduł dla jednej lub dwóch osób.','Gotowy moduł mieszkalny.',109000,25,'7,5 × 3,35 m',2,1,array['mieszkanie'],true,'PUBLISHED',now()),
((select id from c where name='Całoroczne'),'FAMILY 35','family-35','Nowoczesny całoroczny dom dla 2–4 osób.','Salon z kuchnią, sypialnia i łazienka.',149000,35,'10,5 × 3,35 m',3,1,array['mieszkanie'],true,'PUBLISHED',now()),
((select id from c where name='Modułowe'),'FAMILY 50','family-50','Rodzinny dom modułowy z dwiema sypialniami.','Pełnowymiarowa przestrzeń rodzinna.',219000,50,'12,0 × 4,2 m',4,2,array['mieszkanie'],true,'PUBLISHED',now()),
((select id from c where name='Biurowe'),'OFFICE 30','office-30','Gotowe biuro z zapleczem sanitarnym.','Funkcjonalna przestrzeń pracy.',119000,30,'9,0 × 3,35 m',2,0,array['biuro'],false,'PUBLISHED',now()),
((select id from c where name='Usługowe'),'BUSINESS 40','business-40','Elastyczny moduł dla handlu i usług.','Przestrzeń gotowa do rozpoczęcia biznesu.',169000,40,'12,0 × 3,35 m',3,0,array['usługi'],false,'PUBLISHED',now()) returning id,name)
insert into product_images(product_id,url,alt,position,is_main,type) select id,case when name in ('FAMILY 35','OFFICE 30') then '/images/modern-olive.png' else '/images/hero-modular.png' end,name||' — elewacja',0,true,'EXTERIOR' from ins;
insert into faq(question,answer,position) values('Ile trwa produkcja kontenera?','Standardowy proces produkcji zajmuje zwykle 8–12 tygodni.',1),('Czy kontenery są całoroczne?','Tak, modele całoroczne posiadają izolację, ogrzewanie i szczelną stolarkę.',2),('Czy organizujecie transport?','Tak, dostarczamy i montujemy moduły w całej Polsce.',3);
