import Image from "next/image";
import Link from "next/link";
/* eslint-disable @typescript-eslint/no-explicit-any */
import { ArrowDown, ArrowRight, Check, Compass, Factory, Layers3, ShieldCheck, Sparkles } from "lucide-react";
import { getFaqs, getProducts } from "@/lib/data";
import { ProductCard } from "@/components/product-card";
import { SectionHeading } from "@/components/section-heading";
import { FaqList } from "@/components/faq-list";
import { Configurator } from "@/components/configurator";

const process = ["Kontakt", "Dobór modelu", "Projekt i konfiguracja", "Produkcja", "Transport", "Montaż", "Gotowy obiekt"];
export const revalidate = 60;
export default async function Home() {
  const [products, faqs] = await Promise.all([getProducts(), getFaqs()]);
  return <main><section className="relative min-h-[calc(100svh-76px)] overflow-hidden bg-[#171916] text-white"><Image src="/images/hero-modular.png" alt="Nowoczesny całoroczny dom modułowy MODULA" fill priority sizes="100vw" className="object-cover opacity-80"/><div className="absolute inset-0 bg-gradient-to-r from-black/85 via-black/25 to-transparent"/><div className="container relative flex min-h-[calc(100svh-76px)] flex-col justify-end pb-12 pt-28 md:justify-center md:pb-0"><div className="max-w-3xl"><p className="eyebrow !text-white/70">Producent domów modułowych</p><h1 className="display mt-5 text-[clamp(3.4rem,7vw,7.2rem)]">Nowoczesne kontenery.<br/><em className="font-normal text-[#d9c4aa]">Gotowe do życia.</em></h1><p className="mt-7 max-w-xl text-base leading-7 text-white/75 md:text-lg">Projektujemy i produkujemy nowoczesne kontenery mieszkalne, biurowe i użytkowe – od projektu po gotowy obiekt.</p><div className="mt-8 flex flex-wrap gap-3"><Link className="btn btn-light" href="/modele">Zobacz modele <ArrowRight size={17}/></Link><Link className="btn border border-white/50 text-white" href="/wycena">Poproś o wycenę</Link></div></div><a href="#modele" className="absolute bottom-8 right-4 hidden items-center gap-2 text-[11px] uppercase tracking-widest md:flex">Przewiń <ArrowDown size={15}/></a></div></section>
  <section id="modele" className="section"><div className="container"><SectionHeading eyebrow="Wybrane modele" title="Dom dopasowany do Twojego życia" text="Od kompaktowego studia po rodzinny dom. Każdy moduł możemy dopasować funkcjonalnie i materiałowo."/><div className="grid gap-6 md:grid-cols-3">{products.filter(p=>p.featured).slice(0,3).map(p=><ProductCard product={p} key={p.id}/>)}</div><div className="mt-10 text-center"><Link href="/modele" className="btn btn-outline">Zobacz wszystkie modele <ArrowRight size={16}/></Link></div></div></section>
  <section className="section bg-[#f1f0eb]"><div className="container"><SectionHeading eyebrow="Dlaczego MODULA" title="Mniej czekania. Więcej pewności."/><div className="grid gap-px bg-[#d7d8d1] md:grid-cols-4">{[[Factory,"Produkcja pod dachem","Kontrolowane warunki i stała jakość na każdym etapie."],[ShieldCheck,"Jasny standard","Wiesz dokładnie, co obejmuje cena i harmonogram."],[Layers3,"Gotowy obiekt","Instalacje i wnętrze wykonujemy jeszcze w fabryce."],[Compass,"Jedna odpowiedzialność","Projekt, produkcja, transport i montaż w jednym miejscu."]].map(([Icon,t,d]:any)=><div className="bg-[#f1f0eb] p-8" key={t}><Icon size={27} strokeWidth={1.5}/><h3 className="mt-10 text-lg font-bold">{t}</h3><p className="mt-3 text-sm leading-6 text-[#666b63]">{d}</p></div>)}</div></div></section>
  <section className="section bg-[#333b2c] text-white"><div className="container"><SectionHeading eyebrow="Od rozmowy do kluczy" title="Prosty proces. Jeden zespół." light/><div className="grid gap-0 md:grid-cols-7">{process.map((p,i)=><div key={p} className="relative border-l border-white/20 pb-9 pl-5 md:border-l-0 md:border-t md:pb-0 md:pl-0 md:pt-7"><span className="text-xs text-white/45">{String(i+1).padStart(2,"0")}</span><p className="mt-2 text-sm font-bold">{p}</p>{i<6&&<i className="absolute -top-[3px] left-0 hidden h-[5px] w-[5px] rounded-full bg-white md:block"/>}</div>)}</div><Link href="/jak-budujemy" className="btn btn-light mt-12">Poznaj proces <ArrowRight size={16}/></Link></div></section>
  <section className="section"><div className="container grid gap-12 lg:grid-cols-2 lg:items-center"><div className="relative aspect-[4/3]"><Image src="/images/interior-oak.png" alt="Wykończone wnętrze domu modułowego" fill className="object-cover" sizes="50vw"/><div className="absolute -bottom-6 right-0 bg-white p-5 shadow-xl"><span className="display text-4xl">Pod klucz</span><p className="mt-1 text-xs uppercase tracking-wider text-[#777]">gotowe wnętrze</p></div></div><div><p className="eyebrow">Możliwości konfiguracji</p><h2 className="display mt-4 text-5xl md:text-6xl">Twój układ.<br/>Twój standard.</h2><p className="mt-6 max-w-xl text-sm leading-7 text-[#666b63]">Wybieraj elewację, standard wnętrza, instalacje i wyposażenie dodatkowe. Nasz zespół pilnuje, by wszystkie decyzje tworzyły spójną całość.</p><div className="mt-7 grid grid-cols-2 gap-3 text-sm">{["Układ funkcjonalny","Kolor elewacji","Kuchnia i łazienka","Ogrzewanie i klima","Taras i pergola","Smart home"].map(x=><span key={x} className="flex gap-2"><Check size={17} className="text-[#68715a]"/>{x}</span>)}</div><Link className="btn btn-dark mt-8" href="/konfigurator">Skonfiguruj <Sparkles size={16}/></Link></div></div></section>
  <section className="section bg-[#f5f4ef]"><div className="container"><SectionHeading eyebrow="Zaprojektuj swój moduł" title="Kilka wyborów. Jasny kierunek." text="Wstępna konfiguracja zajmuje około dwóch minut. Na jej podstawie przygotujemy dopasowaną rozmowę i wycenę."/><Configurator/></div></section>
  <section className="section"><div className="container grid gap-10 md:grid-cols-2 md:items-center"><div><p className="eyebrow">O firmie</p><h2 className="display mt-4 text-5xl md:text-6xl">Budujemy spokój<br/>na lata.</h2><p className="mt-6 max-w-xl text-sm leading-7 text-[#666b63]">Łączymy precyzję produkcji przemysłowej z wrażliwością dobrej architektury. Każdy moduł przechodzi wieloetapową kontrolę jakości.</p><Link href="/o-nas" className="btn btn-outline mt-8">Poznaj MODULA <ArrowRight size={16}/></Link></div><div className="grid grid-cols-2 gap-px bg-[#dedfd9]">{[["150+","wyprodukowanych modułów"],["5 lat","doświadczenia"],["2500+ m²","wyprodukowanej powierzchni"],["Cała Polska","transport i montaż"]].map(x=><div className="bg-white p-6 md:p-9" key={x[0]}><strong className="display text-4xl md:text-5xl">{x[0]}</strong><p className="mt-3 text-xs leading-5 text-[#666b63]">{x[1]}</p></div>)}</div></div></section>
  <section id="faq" className="section bg-[#f1f0eb]"><div className="container grid gap-10 md:grid-cols-[.8fr_1.2fr]"><div><p className="eyebrow">FAQ</p><h2 className="display mt-4 text-5xl">Zanim zapytasz</h2></div><FaqList items={faqs}/></div></section>
  <section className="bg-[#c49a6c] py-20"><div className="container flex flex-col items-start justify-between gap-8 md:flex-row md:items-end"><div><p className="eyebrow !text-black/55">Zacznijmy rozmowę</p><h2 className="display mt-4 max-w-3xl text-5xl md:text-7xl">Twój nowy obiekt może powstać szybciej, niż myślisz.</h2></div><Link href="/wycena" className="btn btn-dark shrink-0">Poproś o wycenę <ArrowRight size={16}/></Link></div></section></main>;
}
