"use client";
import { useMemo, useState } from "react";
import { SlidersHorizontal, X } from "lucide-react";
import type { Product } from "@/lib/types";
import { ProductCard } from "./product-card";
export function Catalog({ products, initialCategory = "Wszystkie" }: { products: Product[]; initialCategory?: string }) {
  const categories = ["Wszystkie", ...Array.from(new Set(products.map(p=>p.category)))];
  const [category, setCategory] = useState(initialCategory);
  const [maxPrice, setMaxPrice] = useState(300000);
  const [minArea, setMinArea] = useState(0);
  const [rooms, setRooms] = useState(0);
  const [sort, setSort] = useState("featured");
  const [filters, setFilters] = useState(false);
  const visible = useMemo(() => products.filter(p => (category === "Wszystkie" || p.category === category) && p.priceFrom <= maxPrice && (!minArea || p.area >= minArea) && (!rooms || p.rooms >= rooms)).sort((a,b) => sort === "priceAsc" ? a.priceFrom-b.priceFrom : sort === "priceDesc" ? b.priceFrom-a.priceFrom : sort === "area" ? (a.area || Number.MAX_SAFE_INTEGER)-(b.area || Number.MAX_SAFE_INTEGER) : sort === "new" ? b.createdAt.localeCompare(a.createdAt) : Number(b.featured)-Number(a.featured)), [products, category, maxPrice, minArea, rooms, sort]);
  const controls = <><label className="block text-xs font-bold uppercase tracking-wider">Kategoria<select className="field mt-2" value={category} onChange={e=>setCategory(e.target.value)}>{categories.map(x=><option key={x}>{x}</option>)}</select></label><label className="block text-xs font-bold uppercase tracking-wider">Powierzchnia od<select className="field mt-2" value={minArea} onChange={e=>setMinArea(+e.target.value)}><option value="0">Dowolna</option>{[20,25,35,50].map(x=><option key={x} value={x}>{x} m²</option>)}</select></label><label className="block text-xs font-bold uppercase tracking-wider">Cena do<select className="field mt-2" value={maxPrice} onChange={e=>setMaxPrice(+e.target.value)}>{[120000,160000,220000,300000].map(x=><option key={x} value={x}>{x.toLocaleString("pl-PL")} zł</option>)}</select></label><label className="block text-xs font-bold uppercase tracking-wider">Pomieszczenia<select className="field mt-2" value={rooms} onChange={e=>setRooms(+e.target.value)}><option value="0">Dowolnie</option>{[1,2,3,4].map(x=><option key={x} value={x}>{x}+</option>)}</select></label></>;
  return <div><div className="mb-8 flex flex-wrap items-center justify-between gap-4"><p className="text-sm text-[#666b63]">Znaleziono <strong className="text-[#171916]">{visible.length}</strong> modeli</p><div className="flex gap-2"><button onClick={()=>setFilters(true)} className="btn btn-outline lg:hidden"><SlidersHorizontal size={16}/>Filtry</button><select className="field !min-h-11 !w-auto" aria-label="Sortuj" value={sort} onChange={e=>setSort(e.target.value)}><option value="featured">Polecane</option><option value="new">Najnowsze</option><option value="priceAsc">Cena rosnąco</option><option value="priceDesc">Cena malejąco</option><option value="area">Powierzchnia</option></select></div></div><div className="grid gap-8 lg:grid-cols-[240px_1fr]"><aside className="hidden space-y-6 border-r border-[#dedfd9] pr-7 lg:block">{controls}</aside><div>{visible.length ? <div className="grid gap-6 sm:grid-cols-2 xl:grid-cols-3">{visible.map(p=><ProductCard key={p.id} product={p}/>)}</div> : <div className="border border-dashed p-14 text-center"><p className="text-xl font-bold">Brak modeli</p><button className="mt-4 text-sm underline" onClick={()=>{setCategory("Wszystkie");setMaxPrice(300000);setMinArea(0);setRooms(0)}}>Wyczyść filtry</button></div>}</div></div>{filters && <div className="fixed inset-0 z-[80] bg-black/40"><div className="absolute inset-x-0 bottom-0 space-y-5 bg-white p-6"><button onClick={()=>setFilters(false)} className="absolute right-5 top-5"><X/></button><h2 className="text-xl font-bold">Filtry</h2>{controls}<button onClick={()=>setFilters(false)} className="btn btn-dark w-full">Pokaż {visible.length} modeli</button></div></div>}</div>;
}
