"use client";
import Image from "next/image";
import { useEffect, useState } from "react";
import { ChevronLeft, ChevronRight, Expand, X } from "lucide-react";
import type { ProductImage } from "@/lib/types";
export function Gallery({ images }: { images: ProductImage[] }) {
  const [index, setIndex] = useState(0); const [full, setFull] = useState(false);
  const move = (n:number) => setIndex((index+n+images.length)%images.length);
  useEffect(()=>{const key=(e:KeyboardEvent)=>{if(e.key==="Escape")setFull(false);if(full&&e.key==="ArrowLeft")setIndex(i=>(i-1+images.length)%images.length);if(full&&e.key==="ArrowRight")setIndex(i=>(i+1)%images.length)};window.addEventListener("keydown",key);return()=>window.removeEventListener("keydown",key)},[full,images.length]);
  return <><div><div className="group relative aspect-[16/10] overflow-hidden bg-[#eeeee9]"><Image src={images[index]?.url} alt={images[index]?.alt} fill priority className="object-cover" sizes="100vw"/><button onClick={()=>setFull(true)} className="absolute right-4 top-4 grid h-11 w-11 place-items-center bg-white/90" aria-label="Pełny ekran"><Expand size={18}/></button><button onClick={()=>move(-1)} className="absolute left-4 top-1/2 grid h-11 w-11 -translate-y-1/2 place-items-center bg-white/90"><ChevronLeft/></button><button onClick={()=>move(1)} className="absolute right-4 top-1/2 grid h-11 w-11 -translate-y-1/2 place-items-center bg-white/90"><ChevronRight/></button><span className="absolute bottom-4 right-4 bg-black/70 px-3 py-2 text-xs text-white">{index+1} / {images.length}</span></div><div className="mt-3 grid grid-cols-4 gap-3">{images.map((img,i)=><button key={img.id} onClick={()=>setIndex(i)} className={`relative aspect-[4/3] overflow-hidden border-2 ${i===index?"border-[#68715a]":"border-transparent"}`}><Image src={img.url} alt={img.alt} fill className="object-cover" sizes="25vw"/></button>)}</div></div>{full && <div className="fixed inset-0 z-[100] grid place-items-center bg-black/95 p-4"><button onClick={()=>setFull(false)} className="absolute right-5 top-5 z-10 text-white"><X size={32}/></button><div className="relative h-[85vh] w-[95vw]"><Image src={images[index].url} alt={images[index].alt} fill className="object-contain" sizes="100vw"/></div><button onClick={()=>move(-1)} className="absolute left-4 text-white"><ChevronLeft size={40}/></button><button onClick={()=>move(1)} className="absolute right-4 text-white"><ChevronRight size={40}/></button></div>}</>;
}
