import { NextRequest, NextResponse } from "next/server";
import { createClient } from "@supabase/supabase-js";
import { Resend } from "resend";
import { z } from "zod";
const schema=z.object({firstName:z.string().min(2).max(80),lastName:z.string().min(2).max(80),email:z.email(),phone:z.string().min(7).max(20),region:z.string().max(80).optional(),city:z.string().max(100).optional(),model:z.string().max(100).optional(),budget:z.string().max(100).optional(),timeline:z.string().max(100).optional(),message:z.string().max(3000).optional(),website:z.string().max(0).optional()});
const hits=new Map<string,{count:number,time:number}>();
export async function POST(req:NextRequest){try{const ip=req.headers.get("x-forwarded-for")?.split(",")[0]||"local";const now=Date.now();const hit=hits.get(ip);if(hit&&now-hit.time<60000&&hit.count>=5)return NextResponse.json({error:"Zbyt wiele prób"},{status:429});hits.set(ip,{count:hit&&now-hit.time<60000?hit.count+1:1,time:hit&&now-hit.time<60000?hit.time:now});const form=await req.formData();const parsed=schema.safeParse(Object.fromEntries([...form.entries()].filter(([,v])=>typeof v==="string")));if(!parsed.success)return NextResponse.json({error:"Nieprawidłowe dane",details:parsed.error.flatten()},{status:400});const file=form.get("attachment");if(file instanceof File&&file.size){if(file.size>8*1024*1024||!["application/pdf","image/jpeg","image/png"].includes(file.type))return NextResponse.json({error:"Nieprawidłowy załącznik"},{status:400});}
  const url=process.env.NEXT_PUBLIC_SUPABASE_URL,key=process.env.SUPABASE_SERVICE_ROLE_KEY;let inquiryId:string|undefined;if(url&&key){const db=createClient(url,key);let productId:string|undefined;if(parsed.data.model&&/^[a-z0-9-]{1,100}$/.test(parsed.data.model)){const{data:model}=await db.from("products").select("id").eq("slug",parsed.data.model).maybeSingle();productId=model?.id}const {data,error}=await db.from("inquiries").insert({first_name:parsed.data.firstName,last_name:parsed.data.lastName,email:parsed.data.email,phone:parsed.data.phone,region:parsed.data.region,city:parsed.data.city,product_id:productId,budget:parsed.data.budget,timeline:parsed.data.timeline,message:parsed.data.message,status:"NEW"}).select("id").single();if(error)throw error;inquiryId=data.id;if(file instanceof File&&file.size){const safe=`${inquiryId}/${crypto.randomUUID()}-${file.name.replace(/[^a-zA-Z0-9._-]/g,"_")}`;const {error:up}=await db.storage.from("inquiry-attachments").upload(safe,file,{contentType:file.type,upsert:false});if(up)throw up;await db.from("inquiry_attachments").insert({inquiry_id:inquiryId,path:safe,file_name:file.name,mime_type:file.type,size:file.size});}}
  if(process.env.RESEND_API_KEY&&process.env.INQUIRY_EMAIL){const resend=new Resend(process.env.RESEND_API_KEY);await resend.emails.send({from:process.env.RESEND_FROM||"MODULA <formularz@modula.pl>",to:process.env.INQUIRY_EMAIL,subject:`Nowe zapytanie: ${parsed.data.firstName} ${parsed.data.lastName}`,text:`Telefon: ${parsed.data.phone}\nE-mail: ${parsed.data.email}\nModel: ${parsed.data.model||"—"}\nBudżet: ${parsed.data.budget||"—"}\n\n${parsed.data.message||""}`});}
  return NextResponse.json({ok:true,id:inquiryId||"demo"});}catch(error){console.error("inquiry_error",error);return NextResponse.json({error:"Błąd serwera"},{status:500});}}
