create extension if not exists pgcrypto;
create type product_status as enum ('DRAFT','PUBLISHED','ARCHIVED');
create type inquiry_status as enum ('NEW','CONTACTED','OFFER_PREPARATION','OFFER_SENT','WON','LOST');
create type image_type as enum ('EXTERIOR','INTERIOR','PLAN','OTHER');

create table categories(id uuid primary key default gen_random_uuid(),name text not null unique,slug text not null unique,position int not null default 0,created_at timestamptz not null default now());
create table products(id uuid primary key default gen_random_uuid(),category_id uuid references categories(id) on delete set null,name text not null,slug text not null unique,short_description text not null default '',description text not null default '',price_net numeric(12,2),price numeric(12,2),price_from numeric(12,2),price_visible boolean not null default true,area numeric(8,2),dimensions text,rooms int not null default 1,bedrooms int not null default 0,purpose text[] not null default '{}',featured boolean not null default false,status product_status not null default 'DRAFT',meta_title text,meta_description text,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),published_at timestamptz);
create table product_images(id uuid primary key default gen_random_uuid(),product_id uuid not null references products(id) on delete cascade,url text not null,path text,alt text not null default '',position int not null default 0,type image_type not null default 'EXTERIOR',is_main boolean not null default false,created_at timestamptz not null default now());
create unique index one_main_image_per_product on product_images(product_id) where is_main;
create table product_parameters(id uuid primary key default gen_random_uuid(),product_id uuid not null references products(id) on delete cascade,name text not null,value text not null,unit text,position int not null default 0);
create table product_features(id uuid primary key default gen_random_uuid(),product_id uuid not null references products(id) on delete cascade,category text not null,name text not null,position int not null default 0);
create table product_variants(id uuid primary key default gen_random_uuid(),product_id uuid not null references products(id) on delete cascade,name text not null,description text not null default '',price numeric(12,2),position int not null default 0,options jsonb not null default '[]');
create table realizations(id uuid primary key default gen_random_uuid(),product_id uuid references products(id) on delete set null,name text not null,slug text not null unique,location text,year int,area numeric(8,2),description text not null default '',scope text[] not null default '{}',status product_status not null default 'DRAFT',created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table realization_images(id uuid primary key default gen_random_uuid(),realization_id uuid not null references realizations(id) on delete cascade,url text not null,path text,alt text not null default '',position int not null default 0,is_main boolean not null default false);
create table inquiries(id uuid primary key default gen_random_uuid(),first_name text not null,last_name text not null,email text not null,phone text not null,region text,city text,product_id uuid references products(id) on delete set null,configuration jsonb,budget text,timeline text,message text,status inquiry_status not null default 'NEW',created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table inquiry_attachments(id uuid primary key default gen_random_uuid(),inquiry_id uuid not null references inquiries(id) on delete cascade,path text not null,file_name text not null,mime_type text not null,size bigint not null,created_at timestamptz not null default now());
create table inquiry_notes(id uuid primary key default gen_random_uuid(),inquiry_id uuid not null references inquiries(id) on delete cascade,author_id uuid references auth.users(id) on delete set null,note text not null,created_at timestamptz not null default now());
create table faq(id uuid primary key default gen_random_uuid(),question text not null,answer text not null,position int not null default 0,visible boolean not null default true,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table settings(key text primary key,value jsonb not null default '{}',updated_at timestamptz not null default now());
create table profiles(id uuid primary key references auth.users(id) on delete cascade,role text not null default 'editor' check(role in ('admin','editor')),created_at timestamptz not null default now());

create or replace function is_admin() returns boolean language sql stable security definer set search_path=public as $$select exists(select 1 from profiles where id=auth.uid() and role='admin')$$;
create or replace function touch_updated_at() returns trigger language plpgsql as $$begin new.updated_at=now();return new;end$$;
create trigger products_touch before update on products for each row execute function touch_updated_at();
create trigger realizations_touch before update on realizations for each row execute function touch_updated_at();
create trigger inquiries_touch before update on inquiries for each row execute function touch_updated_at();

alter table categories enable row level security;alter table products enable row level security;alter table product_images enable row level security;alter table product_parameters enable row level security;alter table product_features enable row level security;alter table product_variants enable row level security;alter table realizations enable row level security;alter table realization_images enable row level security;alter table inquiries enable row level security;alter table inquiry_attachments enable row level security;alter table inquiry_notes enable row level security;alter table faq enable row level security;alter table settings enable row level security;alter table profiles enable row level security;
create policy "categories public read" on categories for select using(true);
create policy "published products public read" on products for select using(status='PUBLISHED' or is_admin());
create policy "published product images public read" on product_images for select using(exists(select 1 from products p where p.id=product_id and (p.status='PUBLISHED' or is_admin())));
create policy "published parameters public read" on product_parameters for select using(exists(select 1 from products p where p.id=product_id and (p.status='PUBLISHED' or is_admin())));
create policy "published features public read" on product_features for select using(exists(select 1 from products p where p.id=product_id and (p.status='PUBLISHED' or is_admin())));
create policy "published variants public read" on product_variants for select using(exists(select 1 from products p where p.id=product_id and (p.status='PUBLISHED' or is_admin())));
create policy "published realizations public read" on realizations for select using(status='PUBLISHED' or is_admin());
create policy "published realization images public read" on realization_images for select using(exists(select 1 from realizations r where r.id=realization_id and (r.status='PUBLISHED' or is_admin())));
create policy "visible faq public read" on faq for select using(visible or is_admin());
create policy "admins manage categories" on categories for all using(is_admin()) with check(is_admin());
create policy "admins manage products" on products for all using(is_admin()) with check(is_admin());
create policy "admins manage images" on product_images for all using(is_admin()) with check(is_admin());
create policy "admins manage parameters" on product_parameters for all using(is_admin()) with check(is_admin());
create policy "admins manage features" on product_features for all using(is_admin()) with check(is_admin());
create policy "admins manage variants" on product_variants for all using(is_admin()) with check(is_admin());
create policy "admins manage realizations" on realizations for all using(is_admin()) with check(is_admin());
create policy "admins manage realization images" on realization_images for all using(is_admin()) with check(is_admin());
create policy "admins manage inquiries" on inquiries for all using(is_admin()) with check(is_admin());
create policy "admins manage attachments" on inquiry_attachments for all using(is_admin()) with check(is_admin());
create policy "admins manage notes" on inquiry_notes for all using(is_admin()) with check(is_admin());
create policy "admins manage faq" on faq for all using(is_admin()) with check(is_admin());
create policy "admins manage settings" on settings for all using(is_admin()) with check(is_admin());
create policy "profile self read" on profiles for select using(id=auth.uid());

insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types) values('product-images','product-images',true,12582912,array['image/jpeg','image/png','image/webp','image/avif']),('realization-images','realization-images',true,12582912,array['image/jpeg','image/png','image/webp','image/avif']),('inquiry-attachments','inquiry-attachments',false,8388608,array['application/pdf','image/jpeg','image/png']) on conflict(id) do nothing;
create policy "public product media" on storage.objects for select using(bucket_id in ('product-images','realization-images'));
create policy "admins upload media" on storage.objects for insert to authenticated with check(bucket_id in ('product-images','realization-images') and is_admin());
create policy "admins update media" on storage.objects for update to authenticated using(bucket_id in ('product-images','realization-images') and is_admin());
create policy "admins delete media" on storage.objects for delete to authenticated using(bucket_id in ('product-images','realization-images') and is_admin());
create policy "admins read inquiry files" on storage.objects for select to authenticated using(bucket_id='inquiry-attachments' and is_admin());
